### ISSUE TITLE
Internal audit of transaction receipt proof checking

### ISSUE THREAD

**Issue by musnit** [Snowfork/polkadot-ethereum#202]
Based on https://github.com/Snowfork/polkadot-ethereum/pull/182/files#r546965230, our transaction receipt proof verifies transaction inclusion, but does not verifying the transaction / receipt index. This should be fine, but is worth another round of deliberation into potential attack vectors/exploits that may be possible.

**Comment by Rizziepit** [comment]
I thought about this some more and this might be an issue for replay protection, depending on how we implement replay protection. The most natural (and only?) identifier for an event is `block hash + tx index + log`. If we use this to ID an event, replay will be possible because you can change the tx index and re-use a proof. Even if we go in a different direction with replay protection (e.g. the Eth contract assigns IDs to events instead of Substrate deriving IDs), I think it's worth verifying the tx index so that we have the option to safely use it as part of an ID

**Comment by musnit** [comment]
> I thought about this some more and this might be an issue for replay protection, depending on how we implement replay protection. The most natural (and only?) identifier for an event is `block hash + tx index + log`. If we use this to ID an event, replay will be possible because you can change the tx index and re-use a proof. Even if we go in a different direction with replay protection (e.g. the Eth contract assigns IDs to events instead of Substrate deriving IDs), I think it's worth verifying the tx index so that we have the option to safely use it as part of an ID

what about tx_hash?

also if a single tx contains multiple events, can we ensure that they have all been included together?

**Comment by Rizziepit** [comment]
> what about tx_hash

`tx_hash` could be used as part of an identifier, but it's inconvenient because you need the original transaction data to derive it (based on https://github.com/ethereum/go-ethereum/blob/master). So then you also need a transaction proof (as opposed to just needing a receipt proof).

> also if a single tx contains multiple events, can we ensure that they have all been included together?

Theoretically, because we have the entire receipt which contains all events in Substrate. We don't currently do this

**Comment by philipstanislaus** [comment]
I don't think this is a vulnerability if we use replay protection in our messages. Yes, a proof could be reused, but if the message is the same, the nonce is the same, so it will fail at that point.

Even if the tx_id is in provided as an input, it could still be changed, as long as it's not part of the proof, right?

**Comment by philipstanislaus** [comment]
On another note, I just submitted a pending PR comment in #182. That includes a reference implementation of the Ethereum trie in Rust.

**Comment by musnit** [comment]
@Rizziepit this is no longer an issue due to recent channel changes, right?

**Comment by Rizziepit** [comment]
Correct. Closing...
