### ISSUE TITLE
Config descendants-until-final=35 breaks the relayer during E2E tests

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#256]
Just an FYI, a value of `35` caused the relayer to break during E2E tests (segfaults, etc).

_Originally posted by @vgeddes in https://github.com/Snowfork/polkadot-ethereum/pull/255#discussion_r570394247_

**Comment by vgeddes** [comment]
Basically the relayer was trying to process block -35 😜

**Comment by Rizziepit** [comment]
Just so it's documented here: we shouldn't use 35 in e2e tests because it will make the tests very slow by making us wait for 35 blocks before forwarding a message from Eth -> Sub. A number like 0 or 1 is much preferred, and it's fine in an environment where there aren't forks (i.e. ganache). e2e tests run against Ropsten should use > 0. 35 will add 9 - 18 minutes to a test on Ropsten

Regardless, this should be fixed :)
