### ISSUE TITLE
Relayer crashing on "Invalid Transaction"

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/polkadot-ethereum#276]
In my local E2E stack the relayer crashes around every 10-20 minutes with the error below, which makes testing a bit more difficult. It feels like some sort of regression, as I've never seen the error before.

```
time="2021-02-15T11:13:00+02:00" level=info msg="Submitted header to Substrate" blockNumber=200 chain=Substrate
time="2021-02-15T11:13:00+02:00" level=info msg="Shutting down writer..." chain=Substrate
time="2021-02-15T11:13:00+02:00" level=info msg="Shutting down listener..." chain=Ethereum
time="2021-02-15T11:13:00+02:00" level=info msg="Shutting down listener..." chain=Substrate
time="2021-02-15T11:13:00+02:00" level=info msg="Shutting down writer..." chain=Ethereum
time="2021-02-15T11:13:00+02:00" level=error msg="Encountered an unrecoverable failure" error="Invalid Transaction"
```

I traced the error to this [location](https://github.com/Snowfork/polkadot-ethereum/blob/c108a9b7eac57abeeca2799c9ea84f6560ea6cf9/relayer/chain/substrate/outgoing_extrinsics.go#L51) in the extrinsics pool code, which suggests that we're occassionally submitting bad/corrupt data to `submitAndWatch`.

**Comment by Rizziepit** [comment]
"Invalid transaction" errors have always been around, but they might happen more regularly due to the switch to mortal extrinsics in #267. However, I'd expect the location to be [line 92](https://github.com/Snowfork/polkadot-ethereum/blob/c108a9b7eac57abeeca2799c9ea84f6560ea6cf9/relayer/chain/substrate/outgoing_extrinsics.go#L92) rather than [line 51](https://github.com/Snowfork/polkadot-ethereum/blob/c108a9b7eac57abeeca2799c9ea84f6560ea6cf9/relayer/chain/substrate/outgoing_extrinsics.go#L51) 

Are you able to repro consistently within 10 - 20 minutes on the e2e stack? Let's use this issue to collect debugging data. 

Important context: they're most likely not caused by an invalid payload, but rather by other txpool validity checks failing in Substrate. And the other txpool validity checks depend on the state of Substrate's txpool. So the error is transient. We should run Substrate with `ltxpool=trace` so that we have info about the txpool state when the error occurs

**Comment by Rizziepit** [comment]
If the issue relates to mortal extrinsics, you can try reducing `MaxWatchedExtrinsics` to 20 [here](https://github.com/Snowfork/polkadot-ethereum/blob/c108a9b7eac57abeeca2799c9ea84f6560ea6cf9/relayer/chain/substrate/outgoing_extrinsics.go#L17). This will prevent extrinsics from hanging out in the txpool for more than 64 blocks waiting to be processed (their era period is 64 blocks). Or you can increase the era period [here](https://github.com/Snowfork/polkadot-ethereum/blob/c108a9b7eac57abeeca2799c9ea84f6560ea6cf9/relayer/chain/substrate/mortal_era.go#L13).

What are the specs of the machine you're running e2e tests on? I'm wondering if that explains why you are seeing "invalid transaction" after 10 minutes, and I only see it after 12 hours

**Comment by vgeddes** [comment]
Thanks for the pointers Riz. I don't think it was related to mortal extrinsics though. It seems `submitAndWatch` rejected the transactions immediately on line 51.

Strangely I didn't see any of these 'Invalid Transaction' errors today, so it may have been an issue with my machine / dev environment / branch. I'm running an 8-core Ryzen beast with 32GB Ram :)

Will post more information if the issue crops up again.

**Comment by vgeddes** [comment]
We resolved this by reducing MaxWatchedExtrinsics to 20.
